backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: "site_settings"
    label: "Site Settings"
    files:
      - label: "General Settings"
        name: "settings"
        file: "dummy/settings.yml" # This file doesn't need to exist or be used by your site, it's just for CMS validation
        fields:
          - { label: 'Site Name', name: 'site_name', widget: 'string' }
          - label: "Hero Image"
            name: "hero_image"
            widget: "image"
            media_library:
              config:
                multiple: false
          - label: "Site Logo"
            name: "site_logo"
            widget: "image"
            media_library:
              config:
                multiple: false
  - name: 'sponsors'
    label: 'Sponsors'
    folder: 'src/content/sponsors'
    create: true
    fields:
      - label: "Sponsor Logo"
        name: "sponsor_logo"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { label: 'Name', name: 'name', widget: 'string' }
  - name: 'gallery'
    label: 'Gallery'
    folder: 'src/content/gallery'
    create: true
    fields:
      - label: "Gallery Image"
        name: "gallery_image"
        widget: "image"
        media_library:
          config:
            multiple: false
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
    # fields:
    #   - { label: 'Title', name: 'title', widget: 'string' }
    #   - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
    #   - { label: 'Category', name: 'category', widget: 'string' }
    #   - {
    #       label: 'Tags',
    #       name: 'tags',
    #       widget: 'list',
    #       allow_add: true,
    #       allow_delete: true,
    #       collapsed: false,
    #       field: { label: 'Tag', name: 'tag', widget: 'string' },
    #     }
    #   - {
    #       label: "Site Logo",
    #       name: "logo",
    #       widget: "image",
    #       media_library:
    #         config:
    #           multiple: false
    #     }
    #   - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
    #   - { label: 'Author', name: 'author', widget: 'string' }
    #   - { label: 'Content', name: 'body', widget: 'markdown' }
